default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>BUNDLE
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_DEV", "frames_circles_api_development") %>

test:
  <<: *default
  database: frames_circles_api_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("FRAMES_CIRCLES_API_DATABASE_PASSWORD") %>
